<?php
//php如何将数组元素在html标签内输出

header("Content-type:text/html;charset=utf-8");
#$arr=array("Volvo","BMW","Toyota");
$arr=array(
"https://freegpt.one/",
"https://www.mathjax.org/#demo",
"http://lib.shutong121.com/",
"https://chat.openai.com/chat",
"https://www.youtube.com/watch?v=s4jtkzHhLzY&t=256s",
"https://sci-hub.se/",
"https://zlibsearch.1kbtool.com/",
"https://buyhub.xyz/forum/forum.php?mod=viewthread&tid=67&extra=page%3D1",
"https://defiprime.com/exchanges",
"http://quote.eastmoney.com/sz000756.html",
"https://translate.google.com/?sl=en&tl=zh-CN&op=docs",
"https://shop.kongfz.com/396112/",
"http://quote.eastmoney.com/sz002603.html",
"https://leetcode.com/",
"https://colab.research.google.com/?utm_source=scs-index",
"https://pro.coinmarketcap.com/account",
"https://www.bilibili.com/video/BV1Ae4y1D7BU/?vd_source=4def9883c7a9cfc2c5071bbb43f7686d",
"https://breached.to/Thread-Selling-2022-SHGA-Shanghai-Gov-National-Police-database?page=21&highlight=shanghai",
"https://coinmarketcap.com/currencies/dogecoin/",
"https://coinmarketcap.com/currencies/shiba-inu/",
"https://www.coingecko.com/en/coins/gala",
"https://coinmarketcap.com/api/",
"https://coinmarketcap.com/api/documentation/v1/",
"https://unmineable.com/coins/DOGE/address/D8gwrJo8awcUnLPtpgVBL9Lwj4iqJMQpPc",
"https://unmineable.com/coins/ETh/address/0x754EE4ac33809464ea7Ed2Da9A9B032CA035364b",
"https://unmineable.com/coins/GALA/address/0x07BB7552e79A0cADCf4Bb56f6e48A50aa36Fb167",
"https://finance.sina.com.cn/money/forex/hq/BTCETHUSD.shtml",
"https://cn.investing.com/equities/mitsubishi-heavy-industries,-ltd.",
"https://i.finance.sina.com.cn/zixuan,all?sudaref=finance.sina.com.cn&display=0&retcode=0",
"https://mail.qq.com/",
"https://mail.google.com/mail/u/0/#inbox",
"https://www.youtube.com/",
"https://www.bilibili.com/",
"https://www.linkedin.com/feed/",
"https://twitter.com/home",
"https://www.binance.com/zh-CN/markets",
"https://www.google.com/search?q=Coinbase&oq=co&aqs=chrome.0.69i59j69i57j69i60l4j69i65j69i60.692j0j15&sourceid=chrome&ie=UTF-8",
"https://www.coinbase.com/",
"https://www.zhihu.com//",
"https://www.ixigua.com/home/554626371819964?list_entrance=homepage",
"http://www.buyhub.xyz/forum",
"https://buyhub.xyz/wordpress"
);
foreach ($arr as $k=>$v){
echo '<table><tr><a href="'.$v.'">'.$v.'</a> </tr></table>';
}
?>
